### ISSUE TITLE
Support prestart.sh

### ISSUE THREAD

**Issue by alexiri** [tiangolo/meinheld-gunicorn-flask-docker#1]
It would be nice if this image supported prestart.sh, just like uwsgi-nginx-flask-docker. This would allow seamless migration between the two.

**Comment by tiangolo** [comment]
Yes, good idea. I'll add it.

**Comment by tiangolo** [comment]
Done! :heavy_check_mark:

There's now support for `/app/prestart.sh`.

Exactly the same as in `uwsgi-nginx-flask`.

Here are the updated docs: https://github.com/tiangolo/meinheld-gunicorn-flask-docker#custom-appprestartsh

**Comment by RyanBreaker** [comment]
Just a heads up you're not closing these issues once resolved. I am having an issue with the prestart.sh though where regardless of what I have in it, even if it's just an "echo foo" or even empty, I get the following output:
```
(venv) C:\Users\<>\PycharmProjects\<>>docker run ac44-http
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
: not found2: /app/prestart.sh:
```
The container then fails to start entirely.

**Comment by RyanBreaker** [comment]
Nevermind, the issue was actually lineendings in the file. I was building this on Windows and the line endings weren't translating. Switching my editor to use UNIX-style for the file made it work now.

**Comment by tiangolo** [comment]
Thanks for the report @RyanBreaker !
