### ISSUE TITLE
volume mounting

### ISSUE THREAD

**Issue by mkschulze** [tiangolo/meinheld-gunicorn-flask-docker#12]
Hello,

how would one go on with mounting a volume with this image?

In the nginx example it would be required to use a uwsgi file. What about here?

**Comment by tiangolo** [comment]
Hey @mkschulze , thanks for your patience.

You can mount volumes as with any other Docker image.

> In the nginx example it would be required to use a uwsgi file

I'm actually not sure what you refer to with this. Anyway, this image doesn't use Nginx nor uWSGI.
