### ISSUE TITLE
Increase Request Entity Size Limit

### ISSUE THREAD

**Issue by OneTesseractInMultiverse** [tiangolo/meinheld-gunicorn-flask-docker#14]
I'm currently using this image to run a Flask-based application that processes some large JSON files, but it is giving me HTTP 413 error. Which would be the best way to increase the Request Entity Size Limit?

**Comment by rebecca-v** [comment]
> I'm currently using this image to run a Flask-based application that processes some large JSON files, but it is giving me HTTP 413 error. Which would be the best way to increase the Request Entity Size Limit?

same here!  did you find a solution?

**Comment by TY48** [comment]
You can try this in main.py
```
import meinheld
meinheld.set_max_content_length(2**10 * 2**10 * 2**10 * 1) # 1 GB
```

**Comment by rebecca-v** [comment]
Perfect!  Thank you so much, very appreciated

**Comment by OneTesseractInMultiverse** [comment]
Thanks! I think it works :)

**Comment by tiangolo** [comment]
Thanks for the help here @TY48 ! :clap: :bow: 

Thanks for reporting back and closing the issue @OneTesseractInMultiverse  :+1:

**Comment by r1n9w0rm** [comment]
I'm still having this issue after using the code in my main.py that @TY48 recommended.

**Comment by tiangolo** [comment]
@r1n9w0rm please create a new GitHub issue, following the template that will guide you to structure the question in a way that makes it easier to understand your intention and need, to be able to help you better. And also providing a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) that I can copy-paste to replicate it.

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.
