### ISSUE TITLE
Worker type

### ISSUE THREAD

**Issue by OleMussmann** [tiangolo/meinheld-gunicorn-flask-docker#2]
While running a plot.ly dash flask app, the app only loads in the browser if I __don't__ specify a worker type. The `entrypoint.sh` script sets it to `egg:meinheld#gunicorn_worker`. With this option the app stalls on 'Loading ...' in the browser. When running gunicorn inside the container by hand - without the worker type option - it loads just fine.

What is the default worker type, and how do they differ?

**Comment by tiangolo** [comment]
The default worker type is the one included in Gunicorn. Here it's set to `egg:meinheld#gunicorn_worker` to use https://github.com/mopemope/meinheld, which is the fastest (more performance) option for WSGI applications like Flask, Django, etc. By not using Meinheld but the default included in Gunicorn, that performance is lost. And then you would probably be better with https://github.com/tiangolo/uwsgi-nginx-flask-docker directly.

**Note**: For more performance than Meinheld, it would be a framework based on ASGI, like https://github.com/tiangolo/fastapi, running with Uvicorn.

---

Do you have a repo/files with a sample mini-project that I can take a look at? That way I can see and debug what's happening in your use case.

**Comment by OleMussmann** [comment]
Thanks @tiangolo for looking into this.

There's a minimal working example at https://github.com/OleMussmann/meinheld-gunicorn-flask-docker_test

Maybe I'm doing something wrong in the `main.py`? What are good ways to debug?

**Comment by tiangolo** [comment]
Thanks @OleMussmann for your patience!

And thanks for the thorough explanation and debugging example.

It seems this was fixed in Dash v1. I sent you a PR to your debugging repo with the changes.

**Comment by OleMussmann** [comment]
Thank you @tiangolo for following it up. It's been a while since I have looked at this, but I need to do some work on this project soon, so this is great timing.

I think we can close this now.
