### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by casoetan** [tiangolo/meinheld-gunicorn-flask-docker#20]
Any plans to add python 3.8 soon?

**Comment by KingDarBoja** [comment]
In order to support python 3.8, the base docker image from `meinheld-gunicorn-docker` must support it. There is some work in progress waiting to get reviewed and merged on [meinheld-gunicorn-docker#9](https://github.com/tiangolo/meinheld-gunicorn-docker/pull/9) but not sure about it.

**Comment by tiangolo** [comment]
Thanks for the help herre @KingDarBoja !

@casoetan yes, there is now support for Python 3.8 :rocket:
