### ISSUE TITLE
For 2.7 has been added, this chapter in the readme could be removed.

### ISSUE THREAD

**Issue by MakDon** [tiangolo/meinheld-gunicorn-flask-docker#22]
> Python 2.7
> Do you need support for Python 2.7?

> Let me know in an issue and I'll add it.

> But only after knowing that someone actually needs it.

I found that  python 2.7 has been supported in [this commit](https://github.com/tiangolo/meinheld-gunicorn-flask-docker/commit/649c81debc088f499cf47b707098c3b0bd9a62f3) .But this chapter still there.

**Comment by tiangolo** [comment]
Thanks! Good catch. Yes, I just updated that. :fire:
