### ISSUE TITLE
how to use w/ conda

### ISSUE THREAD

**Issue by anthonymobile** [tiangolo/meinheld-gunicorn-flask-docker#25]
been struggling with this — is there a good way to deploy an app using a conda environment into this container?

current dockerfile

```
ADD ./install/environment.yml /tmp/environment.yml
RUN conda env create -f /tmp/environment.yml
RUN echo "source activate $(head -1 /tmp/environment.yml | cut -d' ' -f2)" > ~/.bashrc
ENV PATH /opt/conda/envs/$(head -1 /tmp/environment.yml | cut -d' ' -f2)/bin:$PATH
WORKDIR /
COPY ./app /app
```

an the container cannot find dash when it tries to start the app
```
File "/app/main.py", line 2, in <module>
    import dash
ModuleNotFoundError: No module named 'dash'
```

**Comment by KingDarBoja** [comment]
Hi @anthonymobile 

Use something like this on your dockerfile:

```dockerfile
FROM tiangolo/meinheld-gunicorn:python3.7

LABEL maintainer="Your name"

# Check https://repo.continuum.io/miniconda/ to lookup for
# the MD5 for the provided conda version.
ARG CONDA_VERSION="4.7.12.1"
ARG CONDA_MD5="81c773ff87af5cfac79ab862942ab6b3"

# Install miniconda to /miniconda
RUN wget --quiet "https://repo.anaconda.com/miniconda/Miniconda3-${CONDA_VERSION}-Linux-x86_64.sh" -O ~/miniconda.sh && \
    cd ~/ && \
    echo "$CONDA_MD5 miniconda.sh" | md5sum -c && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean --all && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

ENV PATH /opt/conda/bin:$PATH

# Install conda packages
COPY environment.yml ./

# NOTE: Make sure you install flask, gunicorn and 
# meinheld in your conda env!
RUN /bin/bash -c "\
    conda env update --name base --file environment.yml && conda clean -afy"

# Expose container port made from this image.
ENV LISTEN_PORT 5000
EXPOSE 5000

# Set module name path if different from default
ENV MODULE_NAME app.main
```

**Comment by anthonymobile** [comment]
thank you! just curious though, why would i use this container — if i am reinstalling all those packages again?

**Comment by tiangolo** [comment]
Thanks for the help @KingDarBoja !

@anthonymobile agreed, if you are re-installing everything by hand it's probably less useful. Maybe you could re-use the internal scripts, e.g. https://github.com/tiangolo/meinheld-gunicorn-docker/blob/master/docker-images/start.sh

But you might as well prefer to just do everything from scratch based on your conda environment instead of dealing with both things.

**Comment by KingDarBoja** [comment]
@tiangolo you are right, at the end I wasn't sure why I was using the base image if installing meinheld and gunicorn with conda packages (both are available at conda-forge).

Maybe there should be an alternative config to use with conda with all these steps already in a dockerfile, what do you think?

**Comment by tiangolo** [comment]
Yeah, maybe, although if it is tightly integrated with a custom conda environment I'm not sure if it would add much on top of just having a plain Docker based on Python and adding the configurations by hand... :thinking:
