### ISSUE TITLE
Check for requirements.txt with restart

### ISSUE THREAD

**Issue by andostini** [tiangolo/meinheld-gunicorn-flask-docker#29]
It would be cool if the container checked for a requirements.txt in the app folder everytime I restart the container and pip install the content of the requirements.txt. That would make it so easy to deploy updates to my app.

**Comment by tiangolo** [comment]
The idea is that you build the Docker image with all the dependencies it uses with a fixed version, and then you deploy that. If you need to update dependencies, then you _should_ build the new Docker image.

That way you know you have a full, more or less "static", working Docker image with your app.
