### ISSUE TITLE
gunicorn killing my worker thread at start up

### ISSUE THREAD

**Issue by pjmagee** [tiangolo/meinheld-gunicorn-flask-docker#3]
I have a long running process which loads some training models from Machine Learning and hosts this using Flask, however this docker image is killing my worker process before the models are fully loaded and it keeps restarting the application.

Is there any way to configure the type of worker or how gunicorn monitors the workers not responding that they are still active? 

I see similar issues kind of raised around the web, people are talking about increasing or changing the default --timeout, but i don't see anywhere where that is possible to change?

**Comment by pjmagee** [comment]
I modified the gunicorn config and added a timeout of 300 in the config file on my own docker image, this stopped gunicorn killing the process, which is was doing because the ML models take some time to load into memory. So im closing this.

**Comment by tiangolo** [comment]
Sorry for the delay, I was on a business trip.

I'm glad you solved it! Thanks for reporting back.

**Comment by ericcarboni** [comment]
Hey @pjmagee how did you set the timeout exactly?

**Comment by pjmagee** [comment]
@ericcarboni 

I put this in my docker file to help me in debugging

`RUN sed -i '/errorlog = "-"/a timeout = 300' /gunicorn_conf.py
RUN sed -i '/timeout = 300/a accesslog = "-"' /gunicorn_conf.py
RUN cat /gunicorn_conf.py`

**Comment by Shane-Neeley** [comment]
> I put this in my docker file to help me in debugging

Interesting. @pjmagee so can this a way to change the default timeout without a custom gunicorn_conf.py ?

**Comment by pjmagee** [comment]
Yes that should work @Shane-Neeley
