### ISSUE TITLE
HTTPS in gunicorn config file

### ISSUE THREAD

**Issue by Baukebrenninkmeijer** [tiangolo/meinheld-gunicorn-flask-docker#30]
It is unclear to me how to specify to gunicorn to run in HTTPS mode. I've declared the certfile and keyfile as follows in the config file, which it does seem to read. 
```python
certfile = 'app/cert.pem'
keyfile = 'app/key.pem'
```
but nothing changes when running the container.

**Comment by tiangolo** [comment]
I would suggest you use a Traefik load on top of your container to handle HTTPS for you, including automatic HTTPS certificates with Let's Encrypt.

But anyway, if you still want to do it, I guess you would have to make sure you are copying the files to the Docker image (in your `Dockerfile`), that they exist, that they are correctly read by Gunicorn, etc.

You can probably start a container and use `docker exec` to start a `bash` session inside and check the files, etc.

**Comment by Baukebrenninkmeijer** [comment]
I figured out the issue. It was related with the usage of meinheld. If I run the gunicorn session while specifying the certificates without it, it uses HTTPS. However, using the meinheld workers it did not unfortunately. So in the long term, i'll be searching for an alternative that indeed includes something like traefik.
