### ISSUE TITLE
Enable SSH

### ISSUE THREAD

**Issue by stevozilik** [tiangolo/meinheld-gunicorn-flask-docker#32]
Hi,

I'm testing running this container on Azure App Service. For diagnostics purposes, App Services allows connecting to the containers using SSH as described:
https://docs.microsoft.com/en-us/azure/app-service/containers/configure-custom-container#enable-ssh

What would be the best way to incorporate the required SSH startup to this container?

Regards,
Stefan

**Comment by exesse** [comment]
@stevozilik Man, this container imports python and runs EXACTLY one command. So whats the reason why you can't ctrl-v ctrl-c docker file from this repo, add one missing command and host it on dockerhub?
