### ISSUE TITLE
Long Loading Time for Application

### ISSUE THREAD

**Issue by raby1996** [tiangolo/meinheld-gunicorn-flask-docker#33]
Hello! First off let me thank you the great project, it's a wonderful starting point for those of use using a flask framework.

I'm somewhat new to building web applications using flask, and I am close to finishing one however I've been struggling to figure the cause of what seems like a thread lock, GIL or worker starvation of sorts. Basically these are my symptoms,

The first time I load my webpage it immediately starts loading the relevant content which is some static html with dynamic html that is rendered from ajax calls, so when you login you can visibly see the loading bars telling me that ajax has made the calls to my python routes to load data.

However I notice that if I have more than one session active, lets say I have 2 tabs open to the same page or if more that one user loads the page then the subsequent loads will be stalled, so when I login instead of immediately loading the page and starting the ajax calls it seems like it's frozen/stalled (DOM does not load) and I either have to wait or hard refresh the page several times for it to load correctly and start the ajax calls.

I've spent quite of bit of time trying to figure it out and these are my observations,

- When running the docker image on my localhost opening up multiple sessions does not seem to stall the application from loading

- With the same flask application I attempted to deploy it using your synchronous uswgi framwork and this issue did not occur, each time I attempted to load the page it immediately rendered and my ajax calls proceeded (I have limitations as to why I cannot use this setup and I really built it as a way to test this issue)

- I'm not sure if this is relevant but in the firefox network analysis tab the guilty culprit that stalled the page from rendering was always the same (picture below) (notice it took 2 minues to load, where in uswgi everything loaded immediately )

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/13816852/88259728-b77fc500-cc77-11ea-8abc-b6f0adddb92f.png">

- The only message I get that indicates an error is the following, which is pretty frequent

`[10] [ERROR] ConnectionResetError: [Errno 104] Connection reset by peer`

I attempted to debug it from a browser perspective but came up short and was hoping maybe you could provide some insight into the issue. If you need any additional information from me please let me know ! Thank you!

**Comment by betoksoft** [comment]
Hello,

I've this problem in a certain endpoint, this endpoint works when it is returning some response but when it returns an specific response it takes the same time 2 mins, first i tought that it was some kind of limit in the response size because i was returning a huge JSON document, but i got the same behaviour by returning just None.

I tweaked some of the gunicorn settings to test if any could solve this issue but none seems to fix it:
timeout
graceful-timeout
workers
threads
worker_class (but i couldn't get it changed)

The flask development server works perfect.
This image works perfect: https://github.com/tiangolo/uwsgi-nginx-flask-docker 

This issue is really weird, i'll try to replicate this problem in a minimal setup.

Regards

**Comment by vumaasha** [comment]
application loading takes more than 2 minutes. Below is my gunicorn conf. I am running a flask appbuilder application. Is there any chance to get this working? struggling for day 2 now

```
import json
import multiprocessing
import os

workers_per_core_str = os.getenv("WORKERS_PER_CORE", "2")
max_workers_str = os.getenv("MAX_WORKERS")
use_max_workers = None
if max_workers_str:
    use_max_workers = int(max_workers_str)
web_concurrency_str = os.getenv("WEB_CONCURRENCY", None)

host = os.getenv("HOST", "0.0.0.0")
port = os.getenv("PORT", "80")
bind_env = os.getenv("BIND", None)
use_loglevel = os.getenv("LOG_LEVEL", "debug")
if bind_env:
    use_bind = bind_env
else:
    use_bind = f"{host}:{port}"

cores = multiprocessing.cpu_count()
workers_per_core = float(workers_per_core_str)
default_web_concurrency = workers_per_core * cores
if web_concurrency_str:
    web_concurrency = int(web_concurrency_str)
    assert web_concurrency > 0
else:
    web_concurrency = max(int(default_web_concurrency), 2)
    if use_max_workers:
        web_concurrency = min(web_concurrency, use_max_workers)
accesslog_var = os.getenv("ACCESS_LOG", "-")
use_accesslog = accesslog_var or None
errorlog_var = os.getenv("ERROR_LOG", "-")
use_errorlog = errorlog_var or None
graceful_timeout_str = os.getenv("GRACEFUL_TIMEOUT", "120")
timeout_str = os.getenv("TIMEOUT", "120")
keepalive_str = os.getenv("KEEP_ALIVE", "5")

# Gunicorn config variables
loglevel = use_loglevel
workers = web_concurrency
bind = use_bind
errorlog = use_errorlog
worker_tmp_dir = "/dev/shm"
accesslog = use_accesslog
graceful_timeout = int(graceful_timeout_str)
timeout = int(timeout_str)
keepalive = int(keepalive_str)


# For debugging and testing
log_data = {
    "loglevel": loglevel,
    "workers": workers,
    "bind": bind,
    "graceful_timeout": graceful_timeout,
    "timeout": timeout,
    "keepalive": keepalive,
    "errorlog": errorlog,
    "accesslog": accesslog,
    # Additional, non-gunicorn variables
    "workers_per_core": workers_per_core,
    "use_max_workers": use_max_workers,
    "host": host,
    "port": port,
}
print(json.dumps(log_data))
```

**Comment by tiangolo** [comment]
Hey everyone, loading time is probably related to different things for each case, depending on how you create your application, etc.

If you are still having problems, please create a minimal self-contained example, that can be used to replicate the issue.

**Comment by pramos84** [comment]
Hi, guys. To me, some static contents is taking about 2 min to load, too. The Chrome raises the error above:

![image](https://user-images.githubusercontent.com/17599917/110349313-5e4f8080-8011-11eb-9302-6079872bd4e7.png)

My flask app is quiet simple. Even when loading a single static file in the browser, I can see the error:

![image](https://user-images.githubusercontent.com/17599917/110354018-7aa1ec00-8016-11eb-96ae-f21c9ef5e1a6.png)

My gunicorn configuration is the original from _tiangolo/meinheld-gunicorn-flask_ image. It seems like the server is manipulating data without refreshing data length info.

Anyway, this container image do a great job, and bring impressive performance for my flask app (in dynamic content, at least).

Regards.
