### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by deyvsh** [tiangolo/meinheld-gunicorn-flask-docker#35]
Hi, thanks for sharing this!

Just researching whether we could use it, and - please forgive my ignorance - I can't work out where in the stack I'd do compression. When there's nginx it seems like that's the obvious place, but here I haven't yet got my head around how responsibilities are divided between meinheld and gunicorn.

Any pointers in the right direction would be much appreciated. Thanks!

**Comment by tiangolo** [comment]
I would suggest you put another layer on front of this container (and probably other containers). In my case, I would use [Traefik](https://doc.traefik.io/traefik/), which also handles HTTPS certificates for free. And then set those optimizations in that layer.

Or you could also use an Nginx based one.

But I think any of those would have better performance for that final optimization as those are written in a compiled language.
