### ISSUE TITLE
werkzeug request.query_string is of type `str` rather than `bytes`

### ISSUE THREAD

**Issue by ltalirz** [tiangolo/meinheld-gunicorn-flask-docker#38]
When using the flask `request` object (which comes from the `werkzeug` library), I find that using the `tiangolo/meinheld-gunicorn-flask:python3.8` docker image the `request.query_string` attribute is of type `str`, while the [`werkzeug` documentation](https://werkzeug.palletsprojects.com/en/1.0.x/wrappers/?highlight=query_string#werkzeug.wrappers.BaseRequest.query_string) clearly states that it should be of type `bytes`:

> **query_string**
>   The URL parameters as raw bytestring.

This resulted in issues in migrating an existing application to the `tiangolo/meinheld-gunicorn-flask:python3.8` docker image, since it tried to decode `request.query_string` (`str` objects have no `.decode` method).

I suspect this comes somehow from the combination with `meinheld`, but I open the issue here since this makes it easy to reproduce:

## Minimum working example

`Dockerfile`
```
FROM tiangolo/meinheld-gunicorn-flask:python3.8

COPY main.py /app/main.py
```

`main.py`
```python
from flask import Flask
from flask import request
app = Flask(__name__)

@app.route("/")
def hello():
    msg = " request.query_string is of type {}\n".format(type(request.query_string))

    return msg
```

```bash
docker build  -t query-string .
docker run -d -p 4321:80 query-string
curl localhost:4321
# returns:  request.query_string is of type <class 'str'>
```

**Comment by tiangolo** [comment]
That's quite interesting!

I see that it behaves differently depending on if there's a query string or not.

```console
$ curl "localhost/?qwer=34"
 request.query_string is of type <class 'bytes'>

$ curl localhost           
 request.query_string is of type <class 'str'>
```

---

I tested it here and I was able to confirm that the development Flask server (`flask run`) always returns `request.query_string is of type <class 'bytes'>`.

And Gunicorn alone also always returns `request.query_string is of type <class 'bytes'>`.

I also confirmed with my other image `tiangolo/uwsgi-nginx-flask`, and it behaves as expected, always with: `request.query_string is of type <class 'bytes'>`.

---

I think it's specifically a Meinheld issue. I tested with Meinheld alone, with:

```Python
from flask import Flask
from flask import request
app = Flask(__name__)

@app.route("/")
def hello():
    msg = " request.query_string is of type {}\n".format(type(request.query_string))

    return msg


if __name__ == "__main__":
    from meinheld import server

    server.listen(("0.0.0.0", 80))
    server.run(app)
```

And running that directly as a Python script, it shows the strange behavior.

Given that, it's not really an issue with this image per se, but with Meinheld, you might want to report it there: https://github.com/mopemope/meinheld

**Comment by ltalirz** [comment]
Thanks for looking into this @tiangolo  - I've opened https://github.com/mopemope/meinheld/issues/119

**Comment by tiangolo** [comment]
Thanks for reporting it there @ltalirz! 🚀 

In that case, I think we can close this one, right?

> Sorry for the long delay! 🙈  I wanted to personally address each issue/PR and they piled up through time, but now I'm checking each one in order.

**Comment by ltalirz** [comment]
Sure, keeping the other issue open is good enough
