### ISSUE TITLE
critical vulnerabilities when pushing image to ECR

### ISSUE THREAD

**Issue by thomasfaller** [tiangolo/meinheld-gunicorn-flask-docker#40]
Hey,

To be honest I have no idea if the issue below is related to the docker image at all.

In AWS ECR I get the following critical vulnerabilities when pushing my Docker image to my ECR repo.

`In the Linux kernel 5.0.21, mounting a crafted  btrfs filesystem image and performing some operations can cause  slab-out-of-bounds write access in __btrfs_map_block in  fs/btrfs/volumes.c, because a value of 1 for the number of data stripes  is mishandled.`

`In  the Linux kernel 5.0.21, mounting a crafted f2fs filesystem image can  cause __remove_dirty_segment slab-out-of-bounds write access because an  array is bounded by the number of dirty types (8) but the array index  can exceed this.`

My laptop uses btrfs as filesystem but I never would have thought that it would have a impact on my docker containers (I thought that it was the whole point of containers to be kinda host-agnostic).

Has anyone ever experienced that ? Will I have to use another machine then ?

**Comment by tiangolo** [comment]
Yeah, I wouldn't expect that to be a problem as Docker would use OverlayFS or similar, but I'm actually not sure. Nevertheless, I would think that the issue might also happen with other images, if you try, for example, to build and push a similar image from scratch, do you also get that error?

If you do, then it wouldn't really be related to this repo, but to AWS or to the combination of the setup with your local machine. But yeah, I wouldn't expect the machine you use to affect the final Docker image run somewhere else.
