### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by LunkRat** [tiangolo/meinheld-gunicorn-flask-docker#6]
I have a use-case for using Python 2.7 with this image:

> Do you need support for Python 2.7?
> 
> Let me know in an issue and I'll add it.
> 
> But only after knowing that someone actually needs it.

Thank you and great work!

**Comment by tiangolo** [comment]
Thanks for reporting! I'll have it in mind to add it.

**Comment by tiangolo** [comment]
Python 2.7 is supported now. :tada: 

Have in mind that Python 2.7 (the language itself) will not be supported past this current year.

I hope this image version helps you migrate to Python 3.6 or 3.7 :smile:

**Comment by corstian** [comment]
Whoa perfect timing! Just needed a 2.7 image for something quick 'n dirty. Thanks!

**Comment by tiangolo** [comment]
I think we could close this issue now, right @LunkRat ?

**Comment by LunkRat** [comment]
Thank you @tiangolo !
