### ISSUE TITLE
Let's encrypt certificate on startup

### ISSUE THREAD

**Issue by DahlitzFlorian** [tiangolo/meinheld-gunicorn-flask-docker#7]
Is it possible to add Let's Encrypt certificates on startup with renewing once in a while? Let's say I want to run an image inheriting from this one in production. It would be mandatory to use TLS under the hood.

**Comment by tiangolo** [comment]
There are several details about TLS, for example, you can only have a single program/container managing TLS certificates per IP. So, if you have multiple domains/apps in a single server/cluster of servers, the certificate should be handled by a load balancer/proxy, on top of your Flask container.

That's a common practice, it's called a termination TLS proxy. I suggest you try Traefik, it can acquire the TLS certificates for you, handle renewals, etc. And do it for potentially more than one stack/domain/application.

For more about these HTTPS details, check: https://fastapi.tiangolo.com/deployment/#https

For instructions about setting up a main Traefik in a cluster of one or more Docker nodes (in like 10 minutes), check: https://dockerswarm.rocks/

**Comment by DahlitzFlorian** [comment]
Thanks for the fast response!
I'll definitely check them out. Basically, I only want to run my personal portfolio page in a container on my linode server and let my domain point to it (already happening). Now, I want to use HTTPS as it's in my eyes mandatory. Setting up Docker Swarm and handle the certificates through Traefik.
Thanks again for your help!

**Comment by tiangolo** [comment]
Great! I think we can close this issue now, right?

**Comment by DahlitzFlorian** [comment]
Yes you can, thanks again!
