### ISSUE TITLE
M1 Mac support

### ISSUE THREAD

**Issue by fabiom91** [tiangolo/meinheld-gunicorn-flask-docker#83]
Hi there, I noticed that I can't run your image on my new Macbook with M1 chip.
This is probably due to the `amd64` architecture vs `arm64`. I noticed I was able to use a python 3.10 image. Maybe it's just a matter to upgrade to python 3.10? I saw also there's a PR open here: https://github.com/tiangolo/meinheld-gunicorn-docker/pull/52/files

**Comment by tiangolo** [comment]
Hey there! I just added support for multiarch builds, this should be supported now. :rocket: https://github.com/tiangolo/meinheld-gunicorn-flask-docker/pull/138
